services:

    siciarek.jstrans.twig.extension:
        class: Siciarek\JsTransBundle\Twig\Extension\SiciarekJsTransExtension
        arguments:
            - '@translator.default'
            - '@twig'
            - '%kernel.cache_dir%/translations'
        tags:
            -
                name:   twig.extension
