services:

    siciarek.jstrans.twig.extension:
        class: Siciarek\JsTransBundle\Twig\Extension\SiciarekJsTransExtension
        arguments: [ "@service_container" ]
        tags:
            -
                name:   twig.extension
